// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuLtC3TF2GzKiD6HTOHodcm__t5slQVyw',
    appId: '1:2020470675:web:93711b64da8acbab588266',
    messagingSenderId: '2020470675',
    projectId: 'gonullunet-863c5',
    authDomain: 'gonullunet-863c5.firebaseapp.com',
    storageBucket: 'gonullunet-863c5.firebasestorage.app',
    measurementId: 'G-H76RCWXHDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADKysj5TkdOzmu4DIekG6Ps8gANZnVopU',
    appId: '1:2020470675:android:66d29556c167f4a1588266',
    messagingSenderId: '2020470675',
    projectId: 'gonullunet-863c5',
    storageBucket: 'gonullunet-863c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5wemmzvqdk08vZwbeAvXJxLCy3Wr1R-A',
    appId: '1:2020470675:ios:2a7f0046b0845ce5588266',
    messagingSenderId: '2020470675',
    projectId: 'gonullunet-863c5',
    storageBucket: 'gonullunet-863c5.firebasestorage.app',
    iosBundleId: 'com.example.gonullunetApp',
  );
}
